# Generated by Django 4.2.6 on 2024-01-25 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('LECTURER', 'lecturer'), ('PROVOST', 'provost'), ('MANAGER', 'manager')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(null=True)),
                ('files', models.FileField(upload_to='theses/%Y/%m')),
                ('council', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Theses', to='api.council')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'students'}, related_name='theses', to=settings.AUTH_USER_MODEL)),
                ('supervised', models.ManyToManyField(limit_choices_to={'role': 'lecturer'}, related_name='supervised_theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation_score', models.FloatField()),
                ('content_score', models.FloatField()),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouncilMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_role', models.CharField(max_length=100)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.council')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='council',
            name='members',
            field=models.ManyToManyField(related_name='councils', through='api.CouncilMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
