# Generated by Django 4.2.6 on 2024-01-25 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_council_user_role_thesis_review_councilmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
