# Generated by Django 4.2.6 on 2024-01-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_thesis_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='supervised',
            new_name='supervisor',
        ),
    ]
