# Generated by Django 4.2.6 on 2024-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_supervised_thesis_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
