# Generated by Django 4.2.6 on 2024-01-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_council_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmembership',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.council'),
        ),
        migrations.AlterField(
            model_name='councilmembership',
            name='council_role',
            field=models.CharField(choices=[('CHAIRMAN', 'chairman'), ('SECRETARY', 'secretary'), ('REVIEWER', 'reviewer'), ('MEMBER', 'member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='api.council'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='councilmembership',
            unique_together={('user', 'council')},
        ),
    ]
