# Generated by Django 4.2.6 on 2024-01-27 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0006_alter_councilmembership_council_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='api.council'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='supervisor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, related_name='supervised_theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
