# Generated by Django 4.2.6 on 2024-01-27 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_role_permissions_alter_thesis_abstract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, related_name='supervised_theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
