# Generated by Django 4.2.6 on 2024-01-27 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_thesis_supervisor_thesis_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='supervisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, related_name='supervised_theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
