# Generated by Django 4.2.6 on 2024-01-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_thesis_supervisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_permissions',
        ),
    ]
