# Generated by Django 4.2.6 on 2024-01-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_role_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thesis',
            unique_together={('title', 'council')},
        ),
    ]
