# Generated by Django 4.2.6 on 2024-02-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_thesis_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='abstract',
            new_name='description',
        ),
    ]
