# Generated by Django 4.2.6 on 2024-02-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_abstract_thesis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmembership',
            name='council_role',
            field=models.CharField(choices=[('CHAIRMAN', 'chairman'), ('SECRETARY', 'secretary'), ('REVIEWER', 'reviewer'), ('MEMBER', 'member')], max_length=100, null=True),
        ),
    ]
