# Generated by Django 4.2.6 on 2024-02-20 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_council_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='members',
            field=models.ManyToManyField(related_name='councils', through='api.CouncilMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
