# Generated by Django 4.2.6 on 2024-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_council_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='major',
            field=models.CharField(choices=[('IT', 'Infomation Technology'), ('CS', 'Computer Science'), ('ENG', 'English Language'), ('MKT', 'Marketing')], max_length=200, null=True),
        ),
    ]
