# Generated by Django 4.2.6 on 2024-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_thesis_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmembership',
            name='council_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='major',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
