export const LOAD_STUDENTS_NAME_REQUEST = "LOAD_STUDENTS_NAME_REQUEST";
export const LOAD_STUDENTS_NAME_SUCCESS = "LOAD_STUDENTS_NAME_SUCCESS";
export const LOAD_STUDENTS_NAME_FAIL = "LOAD_STUDENTS_NAME_FAIL";

export const LOAD_LECTURERS_NAME_REQUEST = "LOAD_LECTURERS_NAME_REQUEST";
export const LOAD_LECTURERS_NAME_SUCCESS = "LOAD_LECTURERS_NAME_SUCCESS";
export const LOAD_LECTURERS_NAME_FAIL = "LOAD_LECTURERS_NAME_FAIL";

export const LOAD_COUNCILS_NAME_REQUEST = "LOAD_COUNCILS_NAME_REQUEST";
export const LOAD_COUNCILS_NAME_SUCCESS = "LOAD_COUNCILS_NAME_SUCCESS";
export const LOAD_COUNCILS_NAME_FAIL = "LOAD_COUNCILS_NAME_FAIL";
