export const LOAD_LECTURERS_NAME_REQUEST = "LOAD_LECTURERS_NAME_REQUEST";
export const LOAD_LECTURERS_NAME_SUCCESS = "LOAD_LECTURERS_NAME_SUCCESS";
export const LOAD_LECTURERS_NAME_FAIL = "LOAD_LECTURERS_NAME_FAIL";

export const LOAD_USERS_REQUEST = "LOAD_USERS_REQUEST";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAIL = "LOAD_USERS_FAIL";
