export const OPEN_SEARCH_MODAL = "OPEN_SEARCH_MODAL";
export const CLOSE_SEARCH_MODAL = "CLOSE_SEARCH_MODAL";
export const OPEN_REMOVE_MODAL = "OPEN_REMOVE_MODAL";
export const CLOSE_REMOVE_MODAL = "CLOSE_REMOVE_MODAL";
